import { EnemyConfig, Ability, ShopItem, HydraStats } from './types';

export const ENEMIES: EnemyConfig[] = [
  {
    id: 'doge',
    name: 'Doge',Rename floki to early
    subtitle: 'Much Wow, Very Attack',
    maxHp: 100,
    attack: 10,
    defense: 2,
    dodgeRate: 0.08,
    attackSpeed: 2500,
    tokenReward: 50,
    scoreValue: 100,
  },
  {
    id: 'pepe',
    name: 'Pepe',
    subtitle: 'Feels Good Shield',
    maxHp: 130,
    attack: 11,
    defense: 6,
    dodgeRate: 0.05,
    attackSpeed: 2600,
    tokenReward: 75,
    scoreValue: 200,
  },
  {
    id: 'hug',
    name: 'Hug',
    subtitle: 'Low Volatility Vibes',
    maxHp: 110,
    attack: 9,
    defense: 3,
    dodgeRate: 0.3,
    attackSpeed: 2200,
    healRate: 4,
    tokenReward: 100,
    scoreValue: 300,
  },
  {
    id: 'wowo',
    name: 'Wowo',
    subtitle: 'Pink Panic Seller',
    maxHp: 140,
    attack: 13,
    defense: 2,
    dodgeRate: 0.08,
    attackSpeed: 2000,
    specialThreshold: 0.3,
    specialMultiplier: 2.5,
    tokenReward: 150,
    scoreValue: 500,
  },
  {
    id: 'shiba',
    name: 'Shiba Inu',
    subtitle: 'Such Stealth, Very Dodge',
    maxHp: 150,
    attack: 14,
    defense: 4,
    dodgeRate: 0.25,
    attackSpeed: 1900,
    tokenReward: 200,
    scoreValue: 700,
  },
  {
    id: 'bonk',
    name: 'Bonk',
    subtitle: 'Bonk First, Ask Later',
    maxHp: 170,
    attack: 16,
    defense: 5,
    dodgeRate: 0.1,
    attackSpeed: 1800,
    specialThreshold: 0.4,
    specialMultiplier: 2.0,
    tokenReward: 250,
    scoreValue: 900,
  },
  {
    id: 'pengu',
    name: 'Pengu',
    subtitle: 'Arctic Frost Striker',
    maxHp: 190,
    attack: 15,
    defense: 9,
    dodgeRate: 0.12,
    attackSpeed: 2000,
    healRate: 6,
    tokenReward: 300,
    scoreValue: 1100,
  },
  {
    id: 'floki',
    name: 'Floki',
    subtitle: 'Viking of the Mempool',
    maxHp: 210,
    attack: 18,
    defense: 7,
    dodgeRate: 0.15,
    attackSpeed: 1700,
    specialThreshold: 0.35,
    specialMultiplier: 2.8,
    tokenReward: 350,
    scoreValue: 1400,
  },
  {
    id: 'dog',
    name: 'Dog',
    subtitle: 'Good Boy, Bad Odds',
    maxHp: 240,
    attack: 20,
    defense: 10,
    dodgeRate: 0.18,
    attackSpeed: 1600,
    healRate: 8,
    tokenReward: 400,
    scoreValue: 1700,
  },
  {
    id: 'trump',
    name: 'Trump',
    subtitle: 'Make Crypto Great Again',
    maxHp: 280,
    attack: 22,
    defense: 12,
    dodgeRate: 0.1,
    attackSpeed: 1400,
    specialThreshold: 0.25,
    specialMultiplier: 3.0,
    tokenReward: 500,
    scoreValue: 2000,
  },
];

export const ABILITIES: Ability[] = [
  {
    id: 'liquidity-blast',
    name: 'Liquidity Blast',
    icon: '\u{1F4A5}',
    baseDamage: 28,
    healAmount: 0,
    energyCost: 30,
    cooldownMs: 4500,
    headIndex: 0
  },
  {
    id: 'scalability-strike',
    name: 'Scalability Strike',
    icon: '\u26A1',
    baseDamage: 45,
    healAmount: 0,
    energyCost: 45,
    cooldownMs: 7000,
    headIndex: 1
  },
  {
    id: 'atomic-swap',
    name: 'Atomic Swap',
    icon: '\u{1F504}',
    baseDamage: 18,
    healAmount: 22,
    energyCost: 35,
    cooldownMs: 5500,
    headIndex: 2
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'head-0', name: 'Upgrade Blast Head', description: '+10 Liquidity Blast dmg', cost: 40, maxPurchases: 5 },
  { id: 'head-1', name: 'Upgrade Strike Head', description: '+10 Scalability Strike dmg', cost: 40, maxPurchases: 5 },
  { id: 'head-2', name: 'Upgrade Swap Head', description: '+10 Atomic Swap dmg & heal', cost: 40, maxPurchases: 5 },
  { id: 'max-hp', name: 'Reinforce Scales', description: '+20 Max HP', cost: 30, maxPurchases: 5 },
  { id: 'max-energy', name: 'Expand Energy Core', description: '+15 Max Energy', cost: 35, maxPurchases: 5 },
  { id: 'cooldown', name: 'Temporal Flux', description: '-0.5s all cooldowns', cost: 60, maxPurchases: 4 },
];

export const INITIAL_HYDRA: HydraStats = {
  maxHp: 120,
  hp: 120,
  maxEnergy: 100,
  energy: 100,
  level: 1,
  attack: 12,
  headPower: [0, 0, 0],
};

export const PIXEL_PALETTE: Record<string, string> = {
  'p': '#8b5cf6',
  'P': '#6d28d9',
  'b': '#3b82f6',
  'B': '#1d4ed8',
  'c': '#14b8a6',
  'C': '#06d6a0',
  'w': '#f8fafc',
  'W': '#cbd5e1',
  'g': '#22c55e',
  'G': '#15803d',
  'y': '#fbbf24',
  'Y': '#f59e0b',
  'o': '#fb923c',
  'O': '#ea580c',
  'r': '#ef4444',
  'R': '#dc2626',
  'k': '#f472b6',
  'K': '#ec4899',
  'n': '#1e1b4b',
  'N': '#0f172a',
  'd': '#64748b',
  'D': '#475569',
  'e': '#fde68a',
  'S': '#94a3b8',
  't': '#a78bfa',
  '.': '',
};

export const HYDRA_ART = [
  '.p...p...p.',
  'pcp.pcp.pcp',
  'pwp.pwp.pwp',
  'ppp.ppp.ppp',
  '.ppppppppp.',
  '..ppcpcpp..',
  '..ppppppp..',
  '..ppppppp..',
  '...ppppp...',
  '...pp.pp...',
  '..pp...pp..',
  '..cc...cc..',
];

export const CHARACTER_ART: Record<string, string[]> = {
  hydra: HYDRA_ART,
  doge: [
    '..SSSSS..',
    '.S.ooo.S.',
    'S.ooooo.S',
    'S.o.o.o.S',
    'S..nnn..S',
    '.S.ooo.S.',
    '..SSSSS..',
    '...SSS...',
    '..SS.SS..',
    '.SS...SS.',
    '..SS.SS..',
    '...ooo...',
  ],
  pepe: [
    '..ggggg..',
    '.ggggggg.',
    '.gwg.gwg.',
    '.gng.gng.',
    '.ggggggg.',
    '..grrgg..',
    '..ggggg..',
    'DDgggggDD',
    '.D.ggg.D.',
    '...ggg...',
    '..gg.gg..',
    '.gg...gg.',
  ],
  hug: [
    '..eeeee..',
    '.eeeeeee.',
    '.eDDDDDe.',
    '.eeeeeee.',
    '.ee.e.ee.',
    '..eeeee..',
    '..bbbbb..',
    '.bbbbbbb.',
    '.bbbbbbb.',
    '..bbbbb..',
    '..bb.bb..',
    '.DD..DD..',
  ],
  wowo: [
    '..kkkkk..',
    '.kkkkkkk.',
    '.kwk.kwk.',
    '.kkk.kkk.',
    '.kkkkkkk.',
    '.kk.r.kk.',
    '..kkkkk..',
    '...kkk...',
    '..kkkkk..',
    '.kkkkkkk.',
    '..kk.kk..',
    '.kk...kk.',
  ],
  shiba: [
    '..YYYYY..',
    '.YYYYYYy.',
    '.YwY.YwY.',
    '.YnY.YnY.',
    '.YYYYYYY.',
    '..YoYYY..',
    '..YYYYY..',
    '.YYYYYYY.',
    '..YYYYY..',
    '...YYY...',
    '..YY.YY..',
    '.YY...YY.',
  ],
  bonk: [
    '..ooooo..',
    '.ooooooo.',
    '.owooowo.',
    '.ononono.',
    '.ooooooo.',
    '.oo.R.oo.',
    '..ooooo..',
    '...ooo...',
    '..ooooo..',
    '.ooooooo.',
    '..oo.oo..',
    '.oo...oo.',
  ],
  pengu: [
    '..bbbbb..',
    '.bbbbbbb.',
    '.bwb.bwb.',
    '.bnb.bnb.',
    '.bbbbbbb.',
    '..bWbbb..',
    '..bbbbb..',
    '.WbbbbbW.',
    '.WbbbbbW.',
    '..WWWWW..',
    '..bb.bb..',
    '.bb...bb.',
  ],
  floki: [
    '..ttttt..',
    '.ttttttt.',
    '.twt.twt.',
    '.tnt.tnt.',
    '.ttttttt.',
    '.tt.Y.tt.',
    '..ttttt..',
    '...ttt...',
    '..ttttt..',
    '.ttttttt.',
    '..tt.tt..',
    '.tt...tt.',
  ],
  dog: [
    '..SSSSS..',
    '.SSSSSSS.',
    '.SyS.SyS.',
    '.SnS.SnS.',
    '.SSSSSSS.',
    '..SSgSS..',
    '..SSSSS..',
    '.SSSSSSS.',
    '..SSSSS..',
    '...SSS...',
    '..SS.SS..',
    '.SS...SS.',
  ],
  trump: [
    '..YYYYY..',
    '.YYYYYYY.',
    '.YwY.YwY.',
    '.YnY.YnY.',
    '.YYYYYYY.',
    '.YY.R.YY.',
    '..YYYYY..',
    '...YoY...',
    '..YYYYY..',
    '.YYYYYYY.',
    '..YY.YY..',
    '.YY...YY.',
  ],
};

export const LEADERBOARD_DATA: { name: string; score: number }[] = [];
